### ISSUE TITLE
关于代码高亮的问题

### ISSUE THREAD

**Issue by Passoll** [fordes123/gleaner#10]
首先感谢这么棒的资源！我自己在调整的时候发现，似乎使用Primjs的代码高亮没有办法被部署到网页端口，代码显示有些看不清楚，不知道这里有什么解决办法呢？

**Comment by fordes123** [comment]
可能是和 `assets/css/wp-content.css` 中关于代码高亮的部分css 冲突，尝试删除它们试试

**Comment by Passoll** [comment]
感谢！尝试过了，还是不行，但是到最后发现我用本地插件或者本地部署的高亮就不可以....cdn挂上highlight.js就好了

**Comment by cyolc932** [comment]
> 可能是和 `assets/css/wp-content.css` 中关于代码高亮的部分css 冲突，尝试删除它们试试

请问有考虑增加目录功能吗 还要夜间模式会闪白屏然后才变黑 需要优化一下

**Comment by fordes123** [comment]
文章目录已经在做了，还有些细节需要微调；至于夜间模式的问题暂时还没有好的解决方案

**Comment by fordes123** [comment]
#11
