### ISSUE TITLE
文章显示不全

### ISSUE THREAD

**Issue by xiaoguangzi** [fordes123/gleaner#2]
我昨天发布了七篇文章但是在页面上只能看到五篇文章，在文章末尾可以继续访问文章。想问一下大佬这是什么问题

**Comment by fordes123** [comment]
你可能没有给另外两篇文章指定分类

如果要展示全部文章的话，需要使用归档页。在后台 管理->独立页面，新增一个独立页面，模板选择`归档页`。

**Comment by fordes123** [comment]
> 我昨天发布了七篇文章但是在页面上只能看到五篇文章，在文章末尾可以继续访问文章。想问一下大佬这是什么问题

你可能没有给另外两篇文章指定分类

如果要展示全部文章的话，需要使用归档页。在后台 管理->独立页面，新增一个独立页面，模板指定为: `归档页`

**Comment by xiaoguangzi** [comment]
嗯嗯好的感谢大佬



在 2023-01-02 18:09:04，"以谶" ***@***.***> 写道：

我昨天发布了七篇文章但是在页面上只能看到五篇文章，在文章末尾可以继续访问文章。想问一下大佬这是什么问题

你可能没有给另外两篇文章指定分类

如果要展示全部文章的话，需要使用归档页。在后台 管理->独立页面，新增一个独立页面，模板指定为: 归档页
