### ISSUE TITLE
基于1.2.1的一些问题与建议

### ISSUE THREAD

**Issue by YorkeSun** [fordes123/gleaner#4]
1.一旦切换其他主题，再切换回来 有设置比如“首页app展示”就空了。
2.导航栏位置的建议。再电脑端分辨率较大导航栏在右上角会让首次访问的用户措不及防。建议能做一个选项可以放置在“首页slogan”和“首页app展示”中间。
3.文章页有作者QQ微信之类希望可以在设置里提供选项。
4.文章如果没有标签，希望隐藏“暂无标签”这个标记。
5.主题在控制台——外观 中显示版本号为1.0.0，在设置外观里显示版本号为1.2.0 alpha

**Comment by fordes123** [comment]
首先感谢反馈，下面分条述之：
1. Typecho主题模板设置数据在切换模板的时候被清空。这是Typecho的设计，为了确保不会有原主题数据残留导致现有主题出现故障。如果需要保留模板设置数据请使用 备份/恢复功能
2. 导航栏设计如此，不会考虑修改
3. 文章页的QQ/微信是用于分享文章，不用于展示作者的社交账号
4. 隐藏 `暂无标签` ，这个将在后续版本优化
5. 版本号显示问题，同样将在后续版本优化

**Comment by fordes123** [comment]
已于 [v1.2.3](https://github.com/fordes123/gleaner/releases/tag/v1.2.3) 解决
