### ISSUE TITLE
大佬如何添加友链的

### ISSUE THREAD

**Issue by lingyi06** [fordes123/gleaner#7]
大佬如何添加友链的

**Comment by fordes123** [comment]
你可以在后台新建一个独立页面，作为你的友链页

**Comment by lingyi06** [comment]
但是没有样式，好像就只有文字

**Comment by fordes123** [comment]
`typecho` 支持以 `!!!<-- html tag -->!!!` 的方式在 `markdown` 中嵌入 html 内容，你可以参考 [这篇](https://www.onesrc.cn/p/no-plugin-implementation-of-typecho-independent-friend-chain-page.html) 文章对独立页面进行自定义；或者安装一个第三方的友链插件

**Comment by lingyi06** [comment]
最新版的typecho用不了，友链插件也没有。

**Comment by fordes123** [comment]
请善用搜索。以上方法我在 `typecho1.2.0` 稳定版上测试无误
